config/routes.rb
Rails.application.routes.draw do
  get 'ask', to: 'questions#ask', as: :ask
  get 'answer', to: 'questions#answer', as: :answer
  get 'answers', to: 'questions#answers', as: :answers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
    @question = params[:question]
  end

  ANSWERS = [
    { id: 1, answer: 'Great!' },
    { id: 2, answer: 'Silly question, get dressed and go to work!' },
    { id: 3, answer: "I don't care, get dressed and go to work!" }
  ]

  def answer
    @question = params[:question]

    if params[:question] == 'I am going to work'
      @answer = ANSWERS.find { |answer| answer[:id] == 1 }
    elsif params[:question].include? '?'
      @answer = ANSWERS.find { |answer| answer[:id] == 2 }
    else
      @answer = ANSWERS.find { |answer| answer[:id] == 3 }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>The stupid Coach</h1>
    <%= yield %>
    <p>A stupid coach</p>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>Questions#answer</h1>
<p>Find me in app/views/questions/answer.html.erb</p>

<p><strong> <%= @question %> </strong></p>
<p>- You</p>
<p><%= link_to "Ask", answer_path %></p>
<p><strong>
  <%= @answer[:answer] %>
</strong></p>
<p>- Coach</p>

app/views/questions/ask.html.erb
<h1>Questions#ask</h1>
<p>Find me in app/views/questions/ask.html.erb</p>

<form action="/answer" method="get">
  <!-- <%= hidden_field_tag :authenticity_token, form_authenticity_token %> -->
  <input type="text" name="question" placeholder="Your question">
  <input type="submit" value="Ask">
</form>